/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, BigNumberish, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MockV3Aggregator, MockV3AggregatorInterface } from "../../mocks/MockV3Aggregator.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "decimals_",
        "type": "uint8"
      },
      {
        "internalType": "int256",
        "name": "initialAnswer",
        "type": "int256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "decimals",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "latestRoundData",
    "outputs": [
      {
        "internalType": "uint80",
        "name": "",
        "type": "uint80"
      },
      {
        "internalType": "int256",
        "name": "",
        "type": "int256"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "uint80",
        "name": "",
        "type": "uint80"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "int256",
        "name": "newAnswer",
        "type": "int256"
      }
    ],
    "name": "updateAnswer",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x60a060405234801561000f575f80fd5b506040516102fc3803806102fc83398101604081905261002e916100cf565b6100577f1a2fbba5da0a46875948c21295c9dd3450339f04aa746d7a58c4fb6d472f54da61008f565b60ff82166080526100877fc886578e7e14928a3253cbc49328ef8a9f1674ddc9027c20987108f4e5ad33c161008f565b5f5550610100565b6100a2816100a560201b6101441760201c565b50565b60405181815273c0bec0bec0bec0bec0bec0bec0bec0bec0bec0be905f80602083855afa50505050565b5f80604083850312156100e0575f80fd5b825160ff811681146100f0575f80fd5b6020939093015192949293505050565b6080516101e56101175f395f604801526101e55ff3fe608060405234801561000f575f80fd5b506004361061003f575f3560e01c8063313ce56714610043578063a87a20ce14610081578063feaf968c14610096575b5f80fd5b61006a7f000000000000000000000000000000000000000000000000000000000000000081565b60405160ff90911681526020015b60405180910390f35b61009461008f366004610184565b6100d5565b005b61009e610102565b6040805169ffffffffffffffffffff968716815260208101959095528401929092526060830152909116608082015260a001610078565b6100fe7f5bec128a7d1561fac58da69f7975755bac73af1541e678e1695fcd39ca5a5d2361016e565b5f55565b5f805f805f6101307fdf3d3dc9d45c4f5c72a86e23921bc8596bef453fe24d4da1025ff228a7e2111161016e565b50505f546001949093504292508291508490565b60405181815273c0bec0bec0bec0bec0bec0bec0bec0bec0bec0be905f80602083855afa50505050565b61017781610144565b50565b61018261019b565b565b5f60208284031215610194575f80fd5b5035919050565b634e487b7160e01b5f52605160045260245ffdfea26469706673582212201993cc28ebeea54e1146c03405e25e2100107f5aac9595eb8852073674c0b86a64736f6c634300081a0033";

  
      type MockV3AggregatorConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockV3AggregatorConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockV3Aggregator__factory extends ContractFactory {
    
      constructor(...args: MockV3AggregatorConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(decimals_: BigNumberish, initialAnswer: BigNumberish, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(decimals_, initialAnswer, overrides || {});
    };
    override deploy(decimals_: BigNumberish, initialAnswer: BigNumberish, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(decimals_, initialAnswer, overrides || {}) as Promise<MockV3Aggregator & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockV3Aggregator__factory {
      return super.connect(runner) as MockV3Aggregator__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockV3AggregatorInterface {
      return new Interface(_abi) as MockV3AggregatorInterface;
    }
    
    override attach(address: string | Addressable): MockV3Aggregator {
      return super.attach(address) as MockV3Aggregator;
    }
  static connect(address: string, runner?: ContractRunner | null): MockV3Aggregator {
      return new Contract(address, _abi, runner) as unknown as MockV3Aggregator;
    }
  }

  
  