/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, BigNumberish, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MockV3Aggregator, MockV3AggregatorInterface } from "../../mocks/MockV3Aggregator.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "decimals_",
        "type": "uint8"
      },
      {
        "internalType": "int256",
        "name": "initialAnswer",
        "type": "int256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "decimals",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "latestRoundData",
    "outputs": [
      {
        "internalType": "uint80",
        "name": "",
        "type": "uint80"
      },
      {
        "internalType": "int256",
        "name": "",
        "type": "int256"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "uint80",
        "name": "",
        "type": "uint80"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "int256",
        "name": "newAnswer",
        "type": "int256"
      }
    ],
    "name": "updateAnswer",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x60a0604052348015600e575f80fd5b50604051610188380380610188833981016040819052602b916039565b60ff9091166080525f556068565b5f80604083850312156049575f80fd5b825160ff811681146058575f80fd5b6020939093015192949293505050565b60805161010961007f5f395f604201526101095ff3fe6080604052348015600e575f80fd5b5060043610603a575f3560e01c8063313ce56714603e578063a87a20ce14607b578063feaf968c14608c575b5f80fd5b60647f000000000000000000000000000000000000000000000000000000000000000081565b60405160ff90911681526020015b60405180910390f35b608a608636600460bd565b5f55565b005b5f546040805160018082526020820193909352429181018290526060810191909152608081019190915260a0016072565b5f6020828403121560cc575f80fd5b503591905056fea2646970667358221220952cee89ff83833a224aa4423e92832d14a309af773dc757c47a4c822d9c084664736f6c634300081a0033";

  
      type MockV3AggregatorConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockV3AggregatorConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockV3Aggregator__factory extends ContractFactory {
    
      constructor(...args: MockV3AggregatorConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(decimals_: BigNumberish, initialAnswer: BigNumberish, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(decimals_, initialAnswer, overrides || {});
    };
    override deploy(decimals_: BigNumberish, initialAnswer: BigNumberish, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(decimals_, initialAnswer, overrides || {}) as Promise<MockV3Aggregator & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockV3Aggregator__factory {
      return super.connect(runner) as MockV3Aggregator__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockV3AggregatorInterface {
      return new Interface(_abi) as MockV3AggregatorInterface;
    }
    
    override attach(address: string | Addressable): MockV3Aggregator {
      return super.attach(address) as MockV3Aggregator;
    }
  static connect(address: string, runner?: ContractRunner | null): MockV3Aggregator {
      return new Contract(address, _abi, runner) as unknown as MockV3Aggregator;
    }
  }

  
  