/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ReverseLogisticsInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "MANAGER_ROLE" | "ecoToken" | "ecoTokenUsdPrice18" | "flatFeeUsd18" | "getReturnsByUser" | "getRoleAdmin" | "grantRole" | "hasRole" | "nextReturnId" | "priceFeed" | "registerReturn" | "renounceRole" | "returnsById" | "returnsByUser" | "revokeRole" | "rewardUsd18" | "setPriceFeed" | "setPricingParams" | "supportsInterface" | "usd18ToWei" | "withdrawFees"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FeesWithdrawn" | "PriceFeedUpdated" | "PricingParamsUpdated" | "ReturnRegistered" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MANAGER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'ecoToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'ecoTokenUsdPrice18', values?: undefined): string;
encodeFunctionData(functionFragment: 'flatFeeUsd18', values?: undefined): string;
encodeFunctionData(functionFragment: 'getReturnsByUser', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'nextReturnId', values?: undefined): string;
encodeFunctionData(functionFragment: 'priceFeed', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerReturn', values: [string, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'returnsById', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'returnsByUser', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'rewardUsd18', values?: undefined): string;
encodeFunctionData(functionFragment: 'setPriceFeed', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setPricingParams', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'usd18ToWei', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawFees', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MANAGER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ecoToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ecoTokenUsdPrice18', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'flatFeeUsd18', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReturnsByUser', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextReturnId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'priceFeed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerReturn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'returnsById', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'returnsByUser', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardUsd18', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPriceFeed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPricingParams', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usd18ToWei', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawFees', data: BytesLike): Result;
  }

  
    export namespace FeesWithdrawnEvent {
      export type InputTuple = [to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [to: string, amount: bigint];
      export interface OutputObject {to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PriceFeedUpdatedEvent {
      export type InputTuple = [newPriceFeed: AddressLike];
      export type OutputTuple = [newPriceFeed: string];
      export interface OutputObject {newPriceFeed: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PricingParamsUpdatedEvent {
      export type InputTuple = [flatFeeUsd18: BigNumberish, rewardUsd18: BigNumberish, ecoTokenUsdPrice18: BigNumberish];
      export type OutputTuple = [flatFeeUsd18: bigint, rewardUsd18: bigint, ecoTokenUsdPrice18: bigint];
      export interface OutputObject {flatFeeUsd18: bigint, rewardUsd18: bigint, ecoTokenUsdPrice18: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReturnRegisteredEvent {
      export type InputTuple = [returnId: BigNumberish, user: AddressLike, itemId: string, quantity: BigNumberish, feePaidWei: BigNumberish, rewardAmount: BigNumberish, ethUsdPrice: BigNumberish];
      export type OutputTuple = [returnId: bigint, user: string, itemId: string, quantity: bigint, feePaidWei: bigint, rewardAmount: bigint, ethUsdPrice: bigint];
      export interface OutputObject {returnId: bigint, user: string, itemId: string, quantity: bigint, feePaidWei: bigint, rewardAmount: bigint, ethUsdPrice: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ReverseLogistics extends BaseContract {
    
    connect(runner?: ContractRunner | null): ReverseLogistics;
    waitForDeployment(): Promise<this>;

    interface: ReverseLogisticsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    MANAGER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    ecoToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    ecoTokenUsdPrice18: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    flatFeeUsd18: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getReturnsByUser: TypedContractMethod<
      [user: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    nextReturnId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    priceFeed: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registerReturn: TypedContractMethod<
      [itemId: string, quantity: BigNumberish, metadataURI: string, ],
      [bigint],
      'payable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    returnsById: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint, string] & {user: string, itemId: string, quantity: bigint, timestamp: bigint, ethUsdPrice: bigint, feePaidWei: bigint, rewardAmount: bigint, metadataURI: string }],
      'view'
    >
    

    
    returnsByUser: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    rewardUsd18: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    setPriceFeed: TypedContractMethod<
      [newPriceFeed: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setPricingParams: TypedContractMethod<
      [flatFeeUsd18_: BigNumberish, rewardUsd18_: BigNumberish, ecoTokenUsdPrice18_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    usd18ToWei: TypedContractMethod<
      [usdAmount18: BigNumberish, ethUsdPrice: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    withdrawFees: TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'MANAGER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ecoToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ecoTokenUsdPrice18'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'flatFeeUsd18'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getReturnsByUser'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'nextReturnId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'priceFeed'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerReturn'): TypedContractMethod<
      [itemId: string, quantity: BigNumberish, metadataURI: string, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'returnsById'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint, string] & {user: string, itemId: string, quantity: bigint, timestamp: bigint, ethUsdPrice: bigint, feePaidWei: bigint, rewardAmount: bigint, metadataURI: string }],
      'view'
    >;
getFunction(nameOrSignature: 'returnsByUser'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rewardUsd18'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setPriceFeed'): TypedContractMethod<
      [newPriceFeed: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPricingParams'): TypedContractMethod<
      [flatFeeUsd18_: BigNumberish, rewardUsd18_: BigNumberish, ecoTokenUsdPrice18_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'usd18ToWei'): TypedContractMethod<
      [usdAmount18: BigNumberish, ethUsdPrice: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawFees'): TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'FeesWithdrawn'): TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
getEvent(key: 'PriceFeedUpdated'): TypedContractEvent<PriceFeedUpdatedEvent.InputTuple, PriceFeedUpdatedEvent.OutputTuple, PriceFeedUpdatedEvent.OutputObject>;
getEvent(key: 'PricingParamsUpdated'): TypedContractEvent<PricingParamsUpdatedEvent.InputTuple, PricingParamsUpdatedEvent.OutputTuple, PricingParamsUpdatedEvent.OutputObject>;
getEvent(key: 'ReturnRegistered'): TypedContractEvent<ReturnRegisteredEvent.InputTuple, ReturnRegisteredEvent.OutputTuple, ReturnRegisteredEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;

    filters: {
      
      'FeesWithdrawn(address,uint256)': TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
      FeesWithdrawn: TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
    

      'PriceFeedUpdated(address)': TypedContractEvent<PriceFeedUpdatedEvent.InputTuple, PriceFeedUpdatedEvent.OutputTuple, PriceFeedUpdatedEvent.OutputObject>;
      PriceFeedUpdated: TypedContractEvent<PriceFeedUpdatedEvent.InputTuple, PriceFeedUpdatedEvent.OutputTuple, PriceFeedUpdatedEvent.OutputObject>;
    

      'PricingParamsUpdated(uint256,uint256,uint256)': TypedContractEvent<PricingParamsUpdatedEvent.InputTuple, PricingParamsUpdatedEvent.OutputTuple, PricingParamsUpdatedEvent.OutputObject>;
      PricingParamsUpdated: TypedContractEvent<PricingParamsUpdatedEvent.InputTuple, PricingParamsUpdatedEvent.OutputTuple, PricingParamsUpdatedEvent.OutputObject>;
    

      'ReturnRegistered(uint256,address,string,uint256,uint256,uint256,uint256)': TypedContractEvent<ReturnRegisteredEvent.InputTuple, ReturnRegisteredEvent.OutputTuple, ReturnRegisteredEvent.OutputObject>;
      ReturnRegistered: TypedContractEvent<ReturnRegisteredEvent.InputTuple, ReturnRegisteredEvent.OutputTuple, ReturnRegisteredEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    
    };
  }