/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IEcoBadge, IEcoBadgeInterface } from "../../ReverseLogistics.sol/IEcoBadge.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "recipient",
        "type": "address"
      },
      {
        "internalType": "string",
        "name": "achievementType",
        "type": "string"
      },
      {
        "internalType": "uint256",
        "name": "impactScore",
        "type": "uint256"
      },
      {
        "internalType": "string",
        "name": "metadataURI",
        "type": "string"
      }
    ],
    "name": "mintBadge",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IEcoBadge__factory {
    static readonly abi = _abi;
    static createInterface(): IEcoBadgeInterface {
      return new Interface(_abi) as IEcoBadgeInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IEcoBadge {
      return new Contract(address, _abi, runner) as unknown as IEcoBadge;
    }
  }
  