/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EcoStaking__factory } from './EcoStaking__factory.js';
export { IEcoToken__factory } from './IEcoToken__factory.js';